### ISSUE TITLE
Rename assembly - Idle.Framework to Idle.Resources

### ISSUE THREAD

**Issue by BrayanKhosravian** [tatapuchi/Idle-Developer#49]
**What to refactor**
Rename the assembly `Idle.Framework` to `Idle.Resources`

**How to refactor**
1.) in the file explorer rename the folders and the csproj file
2.) in the sln file rename the strings
3.) rebuild and execute tests

**Why to refactor**
`Common` seems to be a better name

**Comment by tatapuchi** [comment]
Done in the linked PR
